'use strict';
const cfg=window.BLAGO_CONFIG||{};
const safeUrl=s=>{try{const u=new URL(s,location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function photo(p,name){const f=el('div',undefined,'photo'+(p.top===undefined?' regular':''));if(p.top!==undefined){f.style.setProperty('--top',p.top+'%');f.style.setProperty('--mobile-top',(p.mobileTop??p.top)+'%')}const i=el('img');i.src=safeUrl(p.src);i.alt=name;i.loading='lazy';f.append(i);return f}
function amenities(){const a=el('div',undefined,'amenities');['Wi-Fi','Кухня','Стиральная машина'].forEach(s=>a.append(el('span',s)));return a}
async function getProperties(){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(cfg.supabaseUrl+'/rest/v1/properties?visible=eq.true&order=sort_order.asc',{headers:{apikey:cfg.supabaseAnonKey,Authorization:'Bearer '+cfg.supabaseAnonKey}});if(!r.ok)throw Error('Не удалось загрузить объекты. Попробуйте позже.');return r.json()}const r=await fetch('data/properties.json');if(!r.ok)throw Error('Не удалось загрузить каталог.');return r.json()}
async function render(){try{const properties=(await getProperties()).filter(p=>p.visible);const id=new URLSearchParams(location.search).get('property');if(id){const p=properties.find(p=>p.id===id),main=document.querySelector('main');main.replaceChildren();const section=el('section',undefined,'detail wrap'),back=el('a','← Все объекты','back');back.href='./#properties';section.append(back);if(!p){section.append(el('h1','Объект не найден'),el('p','Возможно, он снят с публикации. Посмотрите другие квартиры.'));main.append(section);return}document.title=p.name+' — BLAGO home';section.append(el('div','ЭЙЛАТ · КВАРТИРЫ ДЛЯ КОМАНД','eyebrow'),el('h1',p.name));const gallery=el('div',undefined,'gallery');(p.photos||[]).forEach(x=>gallery.append(photo(x,p.name)));section.append(gallery,amenities());const info=el('div',undefined,'detail-info');info.append(el('h2','О квартире'),el('p',p.description),el('h3',p.price||'Условия по запросу'),el('p','Демонстрационная версия. Приём заявок пока не открыт.'));section.append(info);main.append(section);return}const cards=document.getElementById('cards');cards.replaceChildren();if(!properties.length)cards.append(el('p','Сейчас нет опубликованных объектов.','empty'));properties.forEach(p=>{const a=el('article',undefined,'card');if(p.photos?.length)a.append(photo(p.photos[0],p.name));const c=el('div',undefined,'card-content');c.append(el('h3',p.name),el('p',p.location||'Эйлат','location'),el('p',p.price||'Условия по запросу','price'),amenities());const link=el('a','Подробнее →','outline');link.href='?property='+encodeURIComponent(p.id);c.append(link);a.append(c);cards.append(a)})}catch(e){const target=document.getElementById('cards')||document.querySelector('main');target.replaceChildren(el('p',e.message,'empty'))}}
document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('menu').onclick=()=>{const n=document.getElementById('nav'),open=n.classList.toggle('open');document.getElementById('menu').setAttribute('aria-expanded',String(open))};document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.getElementById('nav').classList.remove('open');document.getElementById('menu').setAttribute('aria-expanded','false')}));render();
