'use strict';
const cfg=window.BLAGO_CONFIG||{},$=s=>document.querySelector(s);let token='',rows=[],editing=null,photos=[],busy=false;
const configured=cfg.supabaseUrl&&cfg.supabaseAnonKey;
function status(t,error=false){$('#status').textContent=t;$('#status').classList.toggle('error',error)}
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
async function request(path,{method='GET',body,headers={}}={}){const r=await fetch(cfg.supabaseUrl+path,{method,headers:{apikey:cfg.supabaseAnonKey,Authorization:'Bearer '+(token||cfg.supabaseAnonKey),'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){if(r.status===401){token='';$('#dashboard').hidden=true;$('#editor').hidden=true;$('#login').hidden=false;throw Error('Войдите снова: срок действия сеанса истёк.')}throw Error('Не удалось выполнить действие. Проверьте соединение и права доступа.')}const t=await r.text();return t?JSON.parse(t):null}
function button(text,fn){const b=node('button',text,'small-btn');b.type='button';b.onclick=fn;return b}
async function refresh(){rows=await request('/rest/v1/properties?order=sort_order.asc');const l=$('#list');l.replaceChildren();if(!rows.length)l.append(node('p','Пока нет объектов. Добавьте первый.'));rows.forEach(p=>{const r=node('div',undefined,'admin-row'),name=node('div');name.append(node('strong',p.name),node('div',p.visible?'Опубликован':'Скрыт','muted'));const actions=node('div',undefined,'actions');actions.append(button('Изменить',()=>edit(p)),button('Удалить',async()=>{if(!confirm('Удалить объект «'+p.name+'»?'))return;try{await request('/rest/v1/properties?id=eq.'+encodeURIComponent(p.id),{method:'DELETE'});await refresh();status('Объект удалён.')}catch(e){status(e.message,true)}}));r.append(name,actions);l.append(r)})}
function renderPhotos(){const box=$('#photos');box.replaceChildren();photos.forEach((p,i)=>{const r=node('div',undefined,'image-row'),im=node('img');im.src=p.src.startsWith('assets/')?'../'+p.src:p.src;im.alt='Фото '+(i+1);r.append(im,node('span',i===0?'Обложка':'Фото '+(i+1)));if(i>0)r.append(button('Выше',()=>{[photos[i-1],photos[i]]=[photos[i],photos[i-1]];renderPhotos()}));if(i<photos.length-1)r.append(button('Ниже',()=>{[photos[i],photos[i+1]]=[photos[i+1],photos[i]];renderPhotos()}));r.append(button('Убрать',()=>{photos.splice(i,1);renderPhotos()}));box.append(r)})}
function edit(p){editing=p.id;photos=structuredClone(p.photos||[]);const f=$('#editor');['name','location','description','price','sort_order'].forEach(k=>f.elements[k].value=p[k]??'');f.elements.visible.checked=p.visible;$('#upload').value='';$('#editor-title').textContent=rows.some(r=>r.id===editing)?'Редактировать объект':'Новый объект';renderPhotos();f.hidden=false;f.scrollIntoView({behavior:'smooth'})}
$('#login').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const data=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email:e.target.elements.email.value,password:e.target.elements.password.value}});token=data.access_token;e.target.elements.password.value='';await refresh();$('#login').hidden=true;$('#dashboard').hidden=false;status('Вы вошли. Изменения после сохранения появятся на сайте.')}catch(err){status(err.message,true)}finally{b.disabled=false}};
$('#logout').onclick=async()=>{try{await request('/auth/v1/logout',{method:'POST'})}catch{}token='';rows=[];photos=[];$('#editor').reset();$('#list').replaceChildren();$('#dashboard').hidden=true;$('#editor').hidden=true;$('#login').hidden=false;status('Вы вышли.')};
$('#add').onclick=()=>edit({id:crypto.randomUUID(),name:'',location:'Эйлат',description:'',price:'Условия по запросу',visible:false,sort_order:rows.length+1,photos:[]});$('#cancel').onclick=()=>{$('#editor').hidden=true;photos=[]};
$('#upload').onchange=async e=>{if(!token||busy)return;busy=true;const submit=$('#editor button[type=submit]');submit.disabled=true;status('Загружаем фотографии…');try{for(const file of e.target.files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Разрешены JPG, PNG и WebP, до 5 МБ на фотографию.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type],path=editing+'/'+crypto.randomUUID()+'.'+ext;const r=await fetch(cfg.supabaseUrl+'/storage/v1/object/property-photos/'+path,{method:'POST',headers:{apikey:cfg.supabaseAnonKey,Authorization:'Bearer '+token,'Content-Type':file.type},body:file});if(!r.ok)throw Error('Не удалось загрузить фото. Проверьте доступ к хранилищу.');photos.push({src:cfg.supabaseUrl+'/storage/v1/object/public/property-photos/'+path});renderPhotos()}status('Фотографии загружены. Нажмите «Сохранить», чтобы добавить их к объекту.')}catch(err){status(err.message,true)}finally{busy=false;submit.disabled=false;e.target.value=''}};
$('#editor').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=e.target,b=e.submitter;b.disabled=true;try{if(f.elements.visible.checked&&!photos.length)throw Error('Добавьте хотя бы одну фотографию перед публикацией.');const p={id:editing,photos,visible:f.elements.visible.checked,sort_order:Number(f.elements.sort_order.value)};for(const k of ['name','location','description','price'])p[k]=f.elements[k].value.trim();await request('/rest/v1/properties?on_conflict=id',{method:'POST',body:p,headers:{Prefer:'resolution=merge-duplicates'}});await refresh();f.hidden=true;status('Сохранено. Изменения доступны на сайте.')}catch(err){status(err.message,true)}finally{b.disabled=false}};
if(configured){$('#login').hidden=false;status('Вход доступен только владельцу.')}else{$('#setup').hidden=false;status('Настройка хранения данных ещё не завершена.')}
