-- The initial BLAGO Home catalogue and image registry are already seeded by
-- the centralize_all_site_images migration in the Frankfurt project.
-- Images are stored in Supabase Storage and referenced through database rows.
