-- The production schema is already deployed to the Frankfurt Supabase project.
-- Project ref: ljundbqybtmcyefgdiix
-- Managed migrations:
--   create_blago_admin_backend
--   centralize_all_site_images
--
-- Do not place service-role or secret keys in this repository.
